<a href="https://colab.research.google.com/github/aniketmondal1210/CodePlayground/blob/main/SVDE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Singular Value Decomposition (SVD) Example using numpy (Not using scikit-learn here)**

Given a rectangular matrix A, it can be factored into the form of A=UΣ(V^T) where U and V^T are orthonormal and Σ is a diagonal matrix of singulr values

In [1]:
import numpy as np

# Set print options for better readability
np.set_printoptions(precision=4, suppress=True)

We will take a simple 3x4 matrix and look at its Singular Value Decomposition with numpy

In [2]:
# Define the input matrix 'a'
a = np.array([[1, 2, 3, 4], [1, 1, 2, 3], [0, 1, 1, 0]])
print("Original Matrix (a):\n", a)

Original Matrix (a):
 [[1 2 3 4]
 [1 1 2 3]
 [0 1 1 0]]


The SVD of this 3x4 matrix seeks a factorization in the form
Here is the correct matrix representation with \(\sigma_3\) in the correct position:  
\
\begin{bmatrix}
1 & 2 & 3 & 4 \\
1 & 1 & 2 & 3 \\
0 & 1 & 1 & 0
\end{bmatrix} =
\begin{bmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{bmatrix} x
\begin{bmatrix}
\sigma_1 & 0 & 0 & 0 \\
0 & \sigma_2 & 0 & 0 \\
0 & 0 & \sigma_3 & 0
\end{bmatrix} x
\begin{bmatrix}
b_{11} & b_{12} & b_{13} & b_{14} \\
b_{21} & b_{22} & b_{23} & b_{24} \\
b_{31} & b_{32} & b_{33} & b_{34} \\
b_{41} & b_{42} & b_{43} & b_{44}
\end{bmatrix}



The number of singular values, σ's is at most 3, since the original matrix has rank of at most 3

The left singular matrix and the right singular matrix are orthonormal

In [3]:
# Perform Singular Value Decomposition (SVD)
u, s, vh = np.linalg.svd(a, full_matrices=True)

In [4]:
# Print singular values
print("\nSingular Values (s):\n", s)


Singular Values (s):
 [6.7509 1.1734 0.2186]


In [5]:
# Print shapes of U, S, and Vh matrices
print("\nShapes of U, S, and Vh matrices:", u.shape, s.shape, vh.shape)


Shapes of U, S, and Vh matrices: (3, 3) (3,) (4, 4)


In [6]:
# Print U matrix and verify its orthonormality
print("\nU Matrix:\n", u)
print("\nU * U^T (Verification of orthonormality):\n", u.dot(u.T))


U Matrix:
 [[ 0.8109  0.0934 -0.5776]
 [ 0.57   -0.3493  0.7437]
 [ 0.1323  0.9324  0.3365]]

U * U^T (Verification of orthonormality):
 [[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0. -0.  1.]]


In [7]:
# Print Vh matrix and verify its orthonormality
print("\nVh Matrix:\n", vh)
print("\nVh * Vh^T (Verification of orthonormality):\n", vh.dot(vh.T))



Vh Matrix:
 [[ 0.2046  0.3443  0.5488  0.7338]
 [-0.2181  0.6561  0.438  -0.5746]
 [ 0.7598 -0.3431  0.4167 -0.3625]
 [-0.5774 -0.5774  0.5774  0.    ]]

Vh * Vh^T (Verification of orthonormality):
 [[ 1.  0. -0.  0.]
 [ 0.  1.  0.  0.]
 [-0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [8]:
# Create a diagonal matrix 'sd' with singular values
sd = np.diag(s)
print("\nDiagonal Matrix (sd) with Singular Values:\n", sd)



Diagonal Matrix (sd) with Singular Values:
 [[6.7509 0.     0.    ]
 [0.     1.1734 0.    ]
 [0.     0.     0.2186]]


In [9]:
# Create a matrix 'sigma' with the same shape as 'a'
# and fill it with the singular values
b = np.zeros((3, 4))
b[:, :-1] = sd  # Fill the first 3 columns with 'sd'
sigma = b
print("\nSigma Matrix:\n", sigma)


Sigma Matrix:
 [[6.7509 0.     0.     0.    ]
 [0.     1.1734 0.     0.    ]
 [0.     0.     0.2186 0.    ]]


In [10]:
# Reconstruct the original matrix 'a' using U, Sigma, and Vh
reconstructed_a = np.dot(np.dot(u, sigma), vh)
print("\nReconstructed Matrix (a):\n", reconstructed_a)


Reconstructed Matrix (a):
 [[ 1.  2.  3.  4.]
 [ 1.  1.  2.  3.]
 [ 0.  1.  1. -0.]]
